kafka:
  bootstrap_servers: '${KAFKA_BOOTSTRAP_SERVERS:-localhost:19092}'
  topic_posts: 'reddit_posts'
  starting_offsets: 'latest'

minio:
  endpoint_url: '${S3_ENDPOINT_URL:-http://localhost:9000}'
  access_key: '${AWS_ACCESS_KEY_ID:-minio}'
  secret_key: '${AWS_SECRET_ACCESS_KEY:-minio123}'
  bucket: '${MINIO_BUCKET:-datalake}'

sink:
  bronze_prefix: 'bronze/reddit_posts'
  silver_prefix: 'silver/reddit_posts'
  gold_prefix: 'gold/reddit_posts'
  gold_backend: 'postgres' # or 'delta'

spark:
  master: '${SPARK_MASTER:-local[*]}'
  shuffle_partitions: ${SPARK_SHUFFLE_PARTITIONS:-4}

  extra_conf:
    spark.sql.extensions: 'io.delta.sql.DeltaSparkSessionExtension'
    spark.sql.catalog.spark_catalog: 'org.apache.spark.sql.delta.catalog.DeltaCatalog'
    spark.sql.session.timeZone: 'UTC'
    spark.sql.adaptive.enabled: 'true'

    # S3A / MinIO
    spark.hadoop.fs.s3a.endpoint: '${S3_ENDPOINT_URL:-http://localhost:9000}'
    spark.hadoop.fs.s3a.access.key: '${AWS_ACCESS_KEY_ID:-minio}'
    spark.hadoop.fs.s3a.secret.key: '${AWS_SECRET_ACCESS_KEY:-minio123}'
    spark.hadoop.fs.s3a.path.style.access: 'true'
    spark.hadoop.fs.s3a.connection.ssl.enabled: 'false'
    spark.hadoop.fs.s3a.aws.credentials.provider: 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider'
    spark.hadoop.fs.s3a.impl: 'org.apache.hadoop.fs.s3a.S3AFileSystem'

    # Delta log store for S3
    spark.delta.logStore.class: 'org.apache.spark.sql.delta.storage.S3SingleDriverLogStore'

app:
  name: 'reddit-pipeline'
  mode: '${APP_MODE:-bronze}'
  checkpoint_base: 's3a://${MINIO_BUCKET:-datalake}/_checkpoints'

reddit:
  client_id: '${REDDIT_CLIENT_ID}'
  client_secret: '${REDDIT_CLIENT_SECRET}'
  user_agent: '${REDDIT_USER_AGENT:-stress-stream/0.1}'
  # subreddits: ['Professors', 'PhD', 'GradSchool', 'csMajors', 'EngineeringStudents']
  subreddits: ['VietNam', 'Vietnamese', 'TroChuyenLinhTinh', 'Saigon', 'HaNoi', 'HoChiMinh']
  query: ''
  search_limit: ${REDDIT_SEARCH_LIMIT:-25}
  poll_interval: ${REDDIT_POLL_INTERVAL:-5} # 5 seconds

model:
  # VI → PhoBERT
  classification_model_vi: "s3a://artifacts/models/20251130T133740Z/phobert_finetuned.zip"

  # EN → DistilBERT
  classification_model_en: "s3a://artifacts/models/20251104T073104Z/distilbert_finetuned.zip"
  
  # Fallback (nên là PhoBERT để an toàn)
  classification_model: '${MODEL_URI:-s3a://artifacts/models/20251130T133740Z/phobert_finetuned.zip}'

  classifier_label_index: ${CLASSIFIER_POS_IDX:-1}
  classifier_batch_size: ${CLASSIFIER_BATCH_SIZE:-16}
  classifier_threshold: ${CLASSIFIER_THRESHOLD:-0.5}

  max_len: 256
  model_version: '${MODEL_VERSION:-phobert-distilbert-combo-finetuned-v1}'

postgres:
  host: '${POSTGRES_HOST:-localhost}'
  port: ${POSTGRES_PORT:-5432}
  database: '${POSTGRES_DB:-postgres}'
  user: '${POSTGRES_USER:-postgres}'
  password: '${POSTGRES_PASSWORD:-postgres}'
